import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { copyFileSync, mkdirSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin

DB Atlas is MIT licensed. This file also contains elkjs (https://github.com/kieler/elkjs),
unmodified, licensed under EPL-2.0 (https://www.eclipse.org/legal/epl-2.0/). See THIRD_PARTY_NOTICES.md.
*/
`;

const prod = process.argv[2] === "production";

// Copies the build output into the test vault after every (re)build.
const TEST_VAULT_PLUGIN_DIR = "test-vault/.obsidian/plugins/db-atlas";
const copyToTestVault = {
	name: "copy-to-test-vault",
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length > 0) return;
			mkdirSync(TEST_VAULT_PLUGIN_DIR, { recursive: true });
			for (const file of ["main.js", "manifest.json", "styles.css"]) {
				copyFileSync(file, `${TEST_VAULT_PLUGIN_DIR}/${file}`);
			}
			console.log(`[db-atlas] build copied to ${TEST_VAULT_PLUGIN_DIR}`);
		});
	},
};

// `import source from "elk-worker-source"`: the ELK worker script as a string, started from a Blob URL.
const elkWorkerSource = {
	name: "elk-worker-source",
	setup(build) {
		build.onResolve({ filter: /^elk-worker-source$/ }, () => ({
			path: resolve("node_modules/elkjs/lib/elk-worker.min.js"),
			namespace: "elk-worker-source",
		}));
		build.onLoad({ filter: /.*/, namespace: "elk-worker-source" }, async (args) => ({
			contents: await readFile(args.path, "utf8"),
			loader: "text",
		}));
	},
};

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		// Optional dependency of elkjs, only used when a worker is requested (never).
		"web-worker",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [elkWorkerSource, copyToTestVault],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
